spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: Hg4R257ARYV0RiM6MpHNf1EyJM4062ACOso7or9dalKnN/446U1IDwBPoRIvk6Pg
    expiration-seconds: 3600