spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
